### ISSUE TITLE
Getting error in code

### ISSUE THREAD

**Issue by roxyadaa** [frank505/SLIM3API#3]
As you have used Illuminate\Database and used the update function for updating into database but same is giving an error 

        $this->guestEntry->where(['id'=>$id])->update([
            "full_name"=>CustomRequestHandler::getParam($request,"name"),
            "email"=>CustomRequestHandler::getParam($request,"email"),
            "comment"=>CustomRequestHandler::getParam($request,"comments"),
        ]);

I am attaching the screenshot of error. Please let me know the solution for it 
![Screenshot 2021-02-06 at 8 13 32 PM](https://user-images.githubusercontent.com/78651168/107121326-d06c6280-68b7-11eb-80cb-01adebc8d9ca.png)

**Comment by rakeshSpace** [comment]
When i'm going to register i faced an issues of internal server error 

`{
    "success": false,
    "error": "INTERNAL_ERROR",
    "message": "something went wrong internally",
    "status_code": "500",
    "trace": "#0 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()\n#1 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Connection.php(322): Illuminate\\Database\\Connection->run()\n#2 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2269): Illuminate\\Database\\Connection->select()\n#3 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2258): Illuminate\\Database\\Query\\Builder->runSelect()\n#4 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2753): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#5 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2257): Illuminate\\Database\\Query\\Builder->onceWithColumns()\n#6 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2680): Illuminate\\Database\\Query\\Builder->get()\n#7 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Query\\Builder.php(2608): Illuminate\\Database\\Query\\Builder->aggregate()\n#8 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\illuminate\\database\\Eloquent\\Builder.php(1422): Illuminate\\Database\\Query\\Builder->count()\n#9 C:\\xampp\\htdocs\\slim-api-oauth1\\app\\Controllers\\AuthController.php(74): Illuminate\\Database\\Eloquent\\Builder->__call()\n#10 C:\\xampp\\htdocs\\slim-api-oauth1\\app\\Controllers\\AuthController.php(46): App\\Controllers\\AuthController->EmailExist()\n#11 [internal function]: App\\Controllers\\AuthController->Register()\n#12 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\Handlers\\Strategies\\RequestResponse.php(40): call_user_func()\n#13 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#14 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(117): Slim\\Route->__invoke()\n#15 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\Route.php(268): Slim\\Route->callMiddlewareStack()\n#16 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\App.php(503): Slim\\Route->run()\n#17 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\tuupola\\callable-handler\\src\\CallableHandler.php(51): Slim\\App->__invoke()\n#18 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\tuupola\\slim-jwt-auth\\src\\JwtAuthentication.php(154): Tuupola\\Middleware\\CallableHandler->handle()\n#19 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\tuupola\\callable-handler\\src\\DoublePassTrait.php(47): Tuupola\\Middleware\\JwtAuthentication->process()\n#20 [internal function]: Tuupola\\Middleware\\JwtAuthentication->__invoke()\n#21 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(57): call_user_func_array()\n#22 [internal function]: Slim\\DeferredCallable->__invoke()\n#23 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func()\n#24 C:\\xampp\\htdocs\\slim-api-oauth1\\config\\middleware.php(23): Slim\\App->Slim\\{closure}()\n#25 [internal function]: Closure->{closure}()\n#26 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(57): call_user_func_array()\n#27 [internal function]: Slim\\DeferredCallable->__invoke()\n#28 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func()\n#29 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()\n#30 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\App.php(392): Slim\\App->callMiddlewareStack()\n#31 C:\\xampp\\htdocs\\slim-api-oauth1\\vendor\\slim\\slim\\Slim\\App.php(297): Slim\\App->process()\n#32 C:\\xampp\\htdocs\\slim-api-oauth1\\config\\bootstrap.php(30): Slim\\App->run()\n#33 C:\\xampp\\htdocs\\slim-api-oauth1\\public\\index.php(3): require_once('...')\n#34 {main}"
}`

**Comment by rakeshSpace** [comment]
When i'm going to register i faced an issues of internal server error of
[response.json](https://github.com/user-attachments/files/18331351/response.json)
